### ISSUE TITLE
Page Speed 

### ISSUE THREAD

**Issue by ghost** [tosunkaya/Tosunkaya.com-CDN#1]
https://github.com/comfusion/hyperdrive

**Comment by tosunkaya** [comment]
do you continue developing, can i try?

**Comment by ghost** [comment]
It's on pause until the following work is fully licensed:
https://github.com/GaryJones/wordpress-plugin-git-flow-svn-deploy

I've pushed all non-confirming libs forward on their licensure. First implementation of Hyperdrive will be on [Chicago Gang History](https://comfusion.io/clients/chicago-gang-history-ii/) hosted on Pantheon.

**Comment by ghost** [comment]
Beta 9 is pretty solid and I'm looking for feedback if you'd like to give it a spin. Note there are some little gotchas right now due to plug-ins like JetPack pulling data externally but not using CDN—and lots of people use it (though I don't personally see much value in JetPack myself).
